# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

# This workflow is published through the LibreCode organization catalog.
# Implementation: LibreCodeCoop/github-workflows

name: Lint stylelint

on: pull_request

permissions:
  contents: read

jobs:
  stylelint:
    uses: LibreCodeCoop/github-workflows/.github/workflows/lint-stylelint.yml@bf6d298f17eacdada7d2f771cad8fe29a11ec09e
